Sprint 1
vabispklp/yap pull request #4
Opened 2021-12-27 09:02 UTC by vabispklp

2021-12-27 16:38 UTC, iTiky requested changes
Есть критические моменты с конкурентностью. Я бы посоветовал просмотреть мой вебинар про архитектуру Го-проекта и переделать текущее решение разделив его по слоям.

2021-12-27 16:38 UTC, iTiky commented on internal/app/storage/storage.go
> +	urlsMap map[string]*model.ShortURL
map в Go не потокобезопасна. Конкурентный запрос к твоему сервису может привести к панике.

2021-12-27 16:38 UTC, iTiky commented on internal/app/storage/storage.go
> +	urlsMap map[string]*model.ShortURL
Я бы не стал тут использовать указатели. Это лишние аллокации и нагрузка на GC. Лучше придерживаться immutable подходя везде, где это возможно. 
Кроме того, если в функцию `AddRedirectLink` передали указатель, а потом сразу присвоили его `nil`, что произойдет?

2021-12-27 16:38 UTC, iTiky commented on internal/app/storage/storage.go
> +var errNotFound = errors.New("original URL not found")
Эта ошибка создаётся, но не используется. Обычно ошибки сервиса выносят в файл `errors.go` и делают их публичными. Тогда на уровне API ты можешь проверить тип ошибки. Например, `if errors.Is(err, storageErrors.ErrNotFound) { // отвечаем 404 }`

2021-12-27 16:38 UTC, iTiky commented on internal/app/storage/storage.go
> +		return nil, errNotFound
А ошибка ли это с точки зрения storage? Ну не нашли, так не нашли. Ты возвращаешь указатель, сервис может проверить его на `nil` и если он пуст, вернуть 404.

2021-12-27 16:38 UTC, iTiky commented on internal/app/storage/storage.go
> +	mu := sync.Mutex{}
Mutex существует в скопе функции, т.е. если вызвать её два раза конкурентно, это будет два разных мьютекса.

2021-12-27 16:38 UTC, iTiky commented on internal/app/storage/storage.go
> +package storage
Я бы придерживался Go-стиля и "оградил" storage интерфейсом. Т.е. я бы делал такую структуру:
```go
/storage
  interface.go
  errors.go
  /inmem - in-memory имплементация интерфейса выше
```

2021-12-27 16:38 UTC, iTiky commented on internal/app/model/model.go
> +	Path        string
Не лучшее имя поля. Т.к. у тебя нет комментариев, стороннему разрабу не понятно что есть Path. Я бы изменил на ID.

2021-12-27 16:38 UTC, iTiky commented on cmd/shortener/main.go
> +	r := chi.NewRouter()
Я бы вынес это на отдельный слой, это разгрузит main.
```go
/api
  server.go
  router.go
  /handlers
```

2021-12-27 16:38 UTC, iTiky commented on cmd/shortener/main.go
> +	r := chi.NewRouter()
А здесь уже создать одной строкой сервер, передать ему все требуемые зависимости.

2021-12-27 16:38 UTC, iTiky commented on cmd/shortener/main.go
> +	log.Fatal(server.ListenAndServe())
Отсутсвует graceful shutdown сервера (реакция на SIGINT)

2021-12-27 16:38 UTC, iTiky commented on internal/app/storage/storage.go
> +package storage
Ты выбрал объявить interface рядом с потребителем, это тоже вариант. Но я бы всё же упаковал это в `inmem`, т.к. когда появится PSQL storage, не очень ясно что будет с этим пакетом.

2021-12-27 16:38 UTC, iTiky commented on internal/app/handler/handler.go
> +type Storage interface {
Storage -> StorageExpected. По моему опыту, так стараются именовать зависимости для большей наглядности.

2021-12-27 16:38 UTC, iTiky commented on internal/app/handler/handler.go
> +func New(storage Storage) *Handler {
Storage может быть `nil`. Лучше на это проверить, чтобы не породить невалидный объект.

2021-12-27 16:38 UTC, iTiky commented on internal/app/handler/handler.go
> +func New(storage Storage) *Handler {
Я бы именовал конструктор `NewHandler`, т.к. в рамках пакета м.б. множество конструкторов (NewServer).

2021-12-27 16:38 UTC, iTiky commented on internal/app/handler/short_url.go
> +func (h *Handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
Тут смешаны разные роли (сервер, роутер, хендлер). Обычно один Handler обрабатывает один ендпоинт и не занимается роутингом.
Я бы разбил метод на два. chi уже выполняет роль роутера, т.е. `switch r.Method` тут не нужен, это должны быть два разных хендлера.

2021-12-27 16:38 UTC, iTiky commented on internal/app/handler/short_url.go
> +			return
Я бы не ставил пустую строку в случае, когда перед return одна строка. Но это вкусовщина.

2021-12-27 16:38 UTC, iTiky commented on internal/app/handler/short_url.go
> +		_, err = url.Parse(stringURL)
Тут лучше писать в Go-стиле: `if _, err := url.Parse(); err != nil {}`

2021-12-27 16:38 UTC, iTiky commented on internal/app/handler/short_url.go
> +		hash := md5.Sum([]byte(stringURL))
Этот блок кода - это бизнес-логика. Я бы вынес это в отдельный слой:
```go
/service
  /shortener
```
Сейчас это кажется лишним, но как только будет больше функционала, код хендлеров будет портянкой текста. В идеале, хендлер должен получить вход, валидировать его и вызвать соответствующий сервис (storage будет зависимостью service в таком случае).

2021-12-27 16:38 UTC, iTiky commented on internal/app/handler/short_url.go
> +		w.WriteHeader(http.StatusMethodNotAllowed)
🤟

2021-12-27 16:38 UTC, iTiky commented on internal/app/handler/short_url_test.go
> +	type wont struct {
wont -> want

2021-12-27 16:38 UTC, iTiky commented on internal/app/handler/short_url_test.go
> +type MockStorage struct {
Посмотри на gomock. Он позволяет генерировать мок-имплементацию по интерфейсу. Тогда эту часть вообще не нужно будет писать и поддерживать.

2021-12-27 16:38 UTC, iTiky commented on cmd/shortener/main.go
> +	r := chi.NewRouter()
Другими словами, main не должен знать как работает тот или иной слой. Его задача инициализировать зависимости и передать их в конструкторы.

2021-12-27 17:57 UTC, vabispklp commented on internal/app/storage/storage.go
> +	urlsMap map[string]*model.ShortURL
Я думал что так наоборот правильнее, что бы при передаче структуры в функцию каждый раз не выделялась память на экземпляр структуры.

Исходя из вопроса, я думал что запись удалиться, но ничего не произошло. Либо я как-то не так проверял дебагером.
`	r.urlsMap[shortURL.Path] = shortURL
	shortURL = nil
	`

2021-12-30 14:27 UTC, iTiky approved these changes
Отличная работа! Перечитай, пожалуйста, все мои комменты. Некоторые - критичны, другие - рекомендации.

2021-12-30 14:27 UTC, iTiky commented on api/rest/handlers/add_url.go
> +		defer r.Body.Close()
defer после чтения! Если при чтении будет ошибка, defer может привести к панике. В Го принято: сначала ошибка, потом defer Close

2021-12-30 14:27 UTC, iTiky commented on api/rest/handlers/add_url_test.go
> +			require.Nil(t, err, "decode error not nil")
🤟

2021-12-30 14:27 UTC, iTiky commented on api/rest/handlers/handler.go
> +		return nil, ErrNilPointerService
Тут можно не заморачиваться с "конкретными" ошибками, т.к. main не будет их проверять, он просто упадет с читабельной для юзера ошибкой. Но это ИМХО.

2021-12-30 14:27 UTC, iTiky commented on api/rest/handlers/handler.go
> +		return nil, ErrNilPointerService
Конкретные нужно вводить там, где их будут проверять, иначе можно с ума сойти =)

2021-12-30 14:27 UTC, iTiky commented on api/rest/server.go
> +	done := make(chan os.Signal, 1)
🚩 флаг! Слои не должны работать с сигналами, это удел строго главного раннера (main). Ты принимаешь контекст, вот пусть main его отменит как получит сигнал. Если каждый слой начнет подписываться на сигналы (представь, что твои зависимости начали это делать), будет ад.

2021-12-30 14:27 UTC, iTiky commented on api/rest/server.go
> +	if !s.started {
`Server` не потокобезопасен и эта функция может запаниковать. Это ерунда в данном случае, т.к. этот объект только main использует. Но чтобы себя обезопасить, обычно указывают контракт в Godoc описании:
```go
// Server implements HTTP server and keeps its dependencies.
// Contract: not thread-safe
type Server struct
```

2022-01-09 10:21 UTC, merged